# Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # microsoft Sql server
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
